(()=>{'use strict';
const $=id=>document.getElementById(id), esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const TAGS=['سهل','صعب','مجلس خاص','تعطيرات نبوية','إنشاد','حضرة ذكر سريعة','حضرة ذكر بطيئة','أداء فريدة'];
const K={notes:'maqamV5.notes',pageNotes:'maqamV5.pageNotes',tags:'maqamV5.tags',favs:'maqamV5.favs',overrides:'maqamV5.overrides',custom:'maqamV5.custom',audioMeta:'maqamV5.audioMeta',markers:'maqamV5.markers',settings:'maqamV5.settings',lists:'maqamV5.lists',admin:'maqamV5.admin'};
function read(k,d){try{const x=JSON.parse(localStorage.getItem(k)||'null');return x!==null?x:d}catch{return d}}function write(k,v){try{localStorage.setItem(k,JSON.stringify(v));return true}catch{return false}}
let notes=read(K.notes,{}),pageNotes=read(K.pageNotes,{}),tags=read(K.tags,{}),favs=new Set(read(K.favs,[])),overrides=read(K.overrides,{}),custom=read(K.custom,[]),audioMeta=read(K.audioMeta,{}),markers=read(K.markers,{}),settings=read(K.settings,{font:1.28,night:false}),lists=read(K.lists,{});
// Safe migration from V4 personal data.
for(const [oldKey,newKey] of [['maqamBookSongNotesV4',K.notes],['maqamBookPageNotesV4',K.pageNotes]]){const old=read(oldKey,{});let changed=false;const dst=newKey===K.notes?notes:pageNotes;for(const [k,v] of Object.entries(old)){if(v&&!dst[k]){dst[k]=v;changed=true}}if(changed)write(newKey,dst)}
const adminParam=new URL(location.href).searchParams.get('admin')==='1';if(adminParam){localStorage.setItem(K.admin,'1')}const ADMIN=localStorage.getItem(K.admin)==='1';
const norm=s=>String(s??'').normalize('NFKC').replace(/[\u0610-\u061A\u064B-\u065F\u0670\u06D6-\u06ED]/g,'').replace(/ـ+/g,'').replace(/[أإآٱ]/g,'ا').replace(/ى/g,'ي').replace(/ؤ/g,'و').replace(/ئ/g,'ي').replace(/ة/g,'ه').replace(/[^\u0600-\u06FF0-9A-Za-z]+/g,' ').replace(/\s+/g,' ').trim().toLowerCase();
function lev(a,b){a=String(a);b=String(b);if(a===b)return 0;if(!a.length)return b.length;if(!b.length)return a.length;let p=Array.from({length:b.length+1},(_,i)=>i),c=new Array(b.length+1);for(let i=1;i<=a.length;i++){c[0]=i;for(let j=1;j<=b.length;j++)c[j]=Math.min(c[j-1]+1,p[j]+1,p[j-1]+(a[i-1]===b[j-1]?0:1));[p,c]=[c,p]}return p[b.length]}
function fuzzyHas(hay,needle){hay=norm(hay);needle=norm(needle);if(!needle)return true;if(hay.includes(needle))return true;const q=needle.split(' ').filter(Boolean),words=hay.split(' ');return q.every(t=>{if(t.length<3)return hay.includes(t);const lim=t.length>=8?2:1;return words.some(w=>Math.abs(w.length-t.length)<=lim&&w[0]===t[0]&&lev(t,w)<=lim)})}
function clip(s,n=280){s=String(s||'').replace(/\s*\n\s*/g,' — ').replace(/\s+/g,' ').trim();return s.length>n?s.slice(0,n).trim()+'…':s}
function highlight(s,q){let out=esc(s);const toks=norm(q).split(' ').filter(x=>x.length>1).slice(0,5);for(const t of toks){const raw=String(s).split(/\s+/).find(w=>norm(w)===t);if(raw)out=out.replace(new RegExp(raw.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'g'),m=>`<mark class="mark">${m}</mark>`)}return out}
function toast(msg){let t=document.getElementById('toastV5');if(!t){t=document.createElement('div');t.id='toastV5';Object.assign(t.style,{position:'fixed',left:'50%',bottom:'calc(22px + env(safe-area-inset-bottom))',transform:'translateX(-50%)',background:'#0f3147',color:'#fff',padding:'10px 16px',borderRadius:'999px',zIndex:2000,boxShadow:'0 10px 30px #0004',maxWidth:'90vw',textAlign:'center'});document.body.appendChild(t)}t.textContent=msg;t.style.display='block';clearTimeout(t._tm);t._tm=setTimeout(()=>t.style.display='none',1800)}

let SECTIONS=[],PAGES=[],BASE_SONGS=[],sectionMap={},pageMap=new Map();
const state={query:'',mode:'smart',maqam:'',tag:'',favOnly:false,page:1,per:30,results:[],pageResults:[]};let currentSong=null,currentPage=1,currentViewerCustom=null,audioObjectUrl='',viewerZoom=1,viewerRotation=0,viewerControls=false,viewerTimer=null;

function dbOpen(){return new Promise((resolve,reject)=>{const r=indexedDB.open('MaqamBookV5',1);r.onupgradeneeded=()=>{const db=r.result;if(!db.objectStoreNames.contains('blobs'))db.createObjectStore('blobs')};r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}
async function blobPut(key,blob){const db=await dbOpen();return new Promise((res,rej)=>{const tx=db.transaction('blobs','readwrite');tx.objectStore('blobs').put(blob,key);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}
async function blobGet(key){const db=await dbOpen();return new Promise((res,rej)=>{const r=db.transaction('blobs').objectStore('blobs').get(key);r.onsuccess=()=>res(r.result||null);r.onerror=()=>rej(r.error)})}
async function blobDel(key){const db=await dbOpen();return new Promise((res,rej)=>{const tx=db.transaction('blobs','readwrite');tx.objectStore('blobs').delete(key);tx.oncomplete=()=>res();tx.onerror=()=>rej(tx.error)})}

function mergedSong(s){const o=overrides[s.id]||{};return {...s,...o,quality:o._manual?{status:'manual_verified',confidence:1,label:'موثق يدوياً ✅'}:(s.quality||{status:'ocr_review',confidence:s.ocrConfidence||0,label:'OCR يحتاج مراجعة ⚠️'})}}
function songs(){return [...BASE_SONGS,...custom].map(mergedSong)}
function songNote(id){return String(notes[id]||'')}function songTags(id){return Array.isArray(tags[id])?tags[id]:[]}function songLists(id){return Object.entries(lists).filter(([,ids])=>Array.isArray(ids)&&ids.includes(id)).map(([name])=>name)}
function songText(s){return [s.title,(s.aliases||[]).join(' '),s.maqam,s.branch,s.rhythm,s.poet,s.composer,s.tape,s.lyrics,s.ocrText,songNote(s.id),songTags(s.id).join(' '),songLists(s.id).join(' ')].filter(Boolean).join('\n')}
function fieldText(s,field){const map={maqam:[s.maqam,s.branch],poet:[s.poet],composer:[s.composer],note:[songNote(s.id)],tag:[songTags(s.id).join(' ')],list:[songLists(s.id).join(' ')],lyrics:[s.lyrics,s.ocrText],rhythm:[s.rhythm],tape:[s.tape],title:[s.title,(s.aliases||[]).join(' ')]};return (map[field]||[songText(s)]).filter(Boolean).join(' ')}
const fieldAliases={'مقام':'maqam','شاعر':'poet','كلمات':'lyrics','ملحن':'composer','الحان':'composer','ألحان':'composer','ملاحظة':'note','ملاحظه':'note','وسم':'tag','إيقاع':'rhythm','ايقاع':'rhythm','وزن':'rhythm','شريط':'tape','عنوان':'title','قائمة':'list','قائمه':'list'};
function parseQuery(raw){const parts=String(raw||'').split('+').map(x=>x.trim()).filter(Boolean);return (parts.length?parts:[String(raw||'').trim()]).filter(Boolean).map(part=>{const m=part.match(/^([^:：]{2,12})[:：]\s*(.+)$/);if(m){const f=fieldAliases[norm(m[1])]||fieldAliases[m[1].trim()];if(f)return{field:f,value:m[2].trim()}}return{field:'all',value:part}})}
function termScore(text,val,mode){const h=norm(text),q=norm(val);if(!q)return 1;if(h.includes(q))return 1000+Math.min(200,q.length*4);if(mode==='phrase')return 0;const toks=q.split(' ').filter(Boolean);if(toks.length&&toks.every(t=>h.includes(t)))return 650+toks.length*15;if(mode==='all')return 0;return fuzzyHas(h,q)?350:0}
function scoreSong(s,raw){const groups=parseQuery(raw);if(!groups.length)return 100;let total=0;for(const g of groups){let sc=termScore(fieldText(s,g.field),g.value,state.mode);if(!sc)return 0;if(g.field==='title')sc+=220;if(g.field==='maqam')sc+=180;if(g.field==='note'||g.field==='tag'||g.field==='list')sc+=150;total+=sc}return total}
function scorePage(p,raw){if(!raw)return 0;const q=norm(raw);const txt=norm([p.text,p.search,(p.titles||[]).join(' '),pageNotes[String(p.n)]].join(' '));if(txt.includes(q))return 800;return state.mode==='smart'&&fuzzyHas(txt,q)?260:0}

function fillFilters(){const mf=$('maqamFilter');for(const s of SECTIONS.filter(x=>!['front','indexes'].includes(x.id))){const o=document.createElement('option');o.value=s.name;o.textContent=s.name;mf.appendChild(o)}const tf=$('tagFilter');for(const t of TAGS){const o=document.createElement('option');o.value=t;o.textContent=t;tf.appendChild(o)}const qt=$('quickTags');qt.innerHTML='';for(const t of TAGS){const b=document.createElement('button');b.className='chip';b.textContent=t;b.onclick=()=>{$('tagFilter').value=$('tagFilter').value===t?'':t;state.tag=$('tagFilter').value;state.page=1;run()};qt.appendChild(b)}}
function qualityBadge(s){const q=s.quality||{};return `<span class="badge ${q.status==='manual_verified'?'quality-ok':'quality-warn'}">${esc(q.label||(q.status==='manual_verified'?'موثق يدوياً ✅':'OCR يحتاج مراجعة ⚠️'))}</span>`}
function card(s){const a=document.createElement('article');a.className='card song';const note=songNote(s.id),tg=songTags(s.id);a.innerHTML=`<div class="card-head"><div><h3>${highlight(s.title||'بدون عنوان',state.query)}</h3><div class="meta-row"><span class="badge">${esc(s.maqam||'غير محدد')}</span>${s.branch?`<span class="badge">${esc(s.branch)}</span>`:''}${qualityBadge(s)}</div></div><button class="fav-star ${favs.has('song:'+s.id)?'on':''}" aria-label="المفضلة">${favs.has('song:'+s.id)?'★':'☆'}</button></div><div class="meta">${[s.poet&&`الشاعر: ${s.poet}`,s.composer&&`الملحن: ${s.composer}`,s.rhythm&&`الإيقاع: ${s.rhythm}`,s.tape&&`الشريط: ${s.tape}`,(s.pdfPages||[]).length&&`PDF: ${(s.pdfPages||[]).join('، ')}`].filter(Boolean).map(esc).join(' • ')}</div>${tg.length?`<div class="tag-row">${tg.map(t=>`<span class="user-tag">${esc(t)}</span>`).join('')}</div>`:''}<div class="song-preview">${highlight(clip(s.lyrics||s.ocrText||'لا يوجد نص مفهرس بعد.'),state.query)}</div>${note?`<div class="note-preview"><strong>ملاحظتي:</strong> ${highlight(note,state.query)}</div>`:''}<div class="actions"><button class="btn gold open-song">عرض النشيد</button>${((s.pdfPages||[]).length||s.sourceType==='personal')?'<button class="btn open-source">الصفحة الأصلية</button>':''}</div>`;a.querySelector('.open-song').onclick=()=>openSong(s.id);const src=a.querySelector('.open-source');if(src)src.onclick=()=>openSongSource(s);a.querySelector('.fav-star').onclick=()=>{toggleFav('song:'+s.id);run()};return a}
function pageCard(p){const a=document.createElement('article');a.className='card';const title=(p.titles||[])[0]||`صفحة PDF ${p.n}`;a.innerHTML=`<div class="card-head"><div><h3>${esc(title)}</h3><div class="meta-row"><span class="badge">${esc(p.maqam||'')}</span><span class="badge">PDF ${p.n}</span></div></div></div><div class="snippet">${highlight(clip(p.text||'',260),state.query)}</div><div class="actions"><button class="btn open">عرض الصفحة الأصلية</button></div>`;a.querySelector('.open').onclick=()=>openPage(p.n);return a}
function run(){state.query=$('q').value.trim();state.maqam=$('maqamFilter').value;state.tag=$('tagFilter').value;let rr=[];for(const s of songs()){if(state.maqam&&norm(s.maqam)!==norm(state.maqam))continue;if(state.tag&&!songTags(s.id).includes(state.tag))continue;if(state.favOnly&&!favs.has('song:'+s.id))continue;const sc=scoreSong(s,state.query);if(sc>0)rr.push({s,sc})}rr.sort((a,b)=>b.sc-a.sc||Math.min(...(a.s.pdfPages||[9999]))-Math.min(...(b.s.pdfPages||[9999])));state.results=rr;state.pageResults=[];if(state.query&&rr.length===0){for(const p of PAGES){if(state.maqam&&norm(p.maqam)!==norm(state.maqam))continue;const sc=scorePage(p,state.query);if(sc>0)state.pageResults.push({p,sc})}state.pageResults.sort((a,b)=>b.sc-a.sc||a.p.n-b.p.n)}render()}
function render(){const root=$('results');root.innerHTML='';const total=state.results.length,start=(state.page-1)*state.per,end=Math.min(total,start+state.per);$('resultCount').textContent=`${total} ${total===1?'نتيجة':'نتيجة'}`;$('resultsTitle').textContent=state.query?`نتائج «${state.query}»`:state.favOnly?'المفضلة':state.maqam?`مقام ${state.maqam}`:'الأناشيد والقصائد';$('resultSummary').innerHTML=state.query?`وجدنا <strong>${total}</strong> نشيداً/قصيدةً مطابقة في الفهرس المنظم${total?'. اضغط على أي نتيجة لعرض الكلمات والمعلومات والمصدر.':'.'}`:`الفهرس المنظم يحتوي <strong>${songs().length}</strong> سجلاً؛ السجلات غير الموثقة يدوياً تبقى مميزة بوضوح.`;if(total){for(const x of state.results.slice(start,end))root.appendChild(card(x.s))}else if(state.pageResults.length){const msg=document.createElement('div');msg.className='empty';msg.innerHTML=`لم نجد سجلاً منظماً مؤكداً، لكن وجدنا الكلمة في <strong>${state.pageResults.length}</strong> صفحة من صور الكتاب. هذه نتائج صفحات احتياطية:`;root.appendChild(msg);for(const x of state.pageResults.slice(0,20))root.appendChild(pageCard(x.p))}else{root.innerHTML='<div class="empty">لا توجد نتائج. جرّب كلمة أقصر، أو بحثاً مركباً مثل «راست + رسول الله».</div>'}const pg=$('pager');pg.innerHTML='';const pages=Math.ceil(total/state.per);if(pages>1){const prev=document.createElement('button');prev.className='btn';prev.textContent='السابق';prev.disabled=state.page<=1;prev.onclick=()=>{state.page--;render();window.scrollTo({top:0})};const label=document.createElement('span');label.className='btn';label.textContent=`${state.page} / ${pages}`;const next=document.createElement('button');next.className='btn';next.textContent='التالي';next.disabled=state.page>=pages;next.onclick=()=>{state.page++;render();window.scrollTo({top:0})};pg.append(prev,label,next)}document.querySelectorAll('#quickTags .chip').forEach(b=>b.classList.toggle('on',b.textContent===state.tag))}
function toggleFav(k){favs.has(k)?favs.delete(k):favs.add(k);write(K.favs,[...favs])}

function buildSuggestions(){const q=norm($('q').value);const box=$('autocomplete');if(q.length<2){box.classList.add('hidden');return}const pool=[];for(const s of songs()){let score=0,nt=norm(s.title);if(nt.startsWith(q))score=100;else if(nt.includes(q))score=80;else if(fuzzyHas(nt,q))score=50;if(score)pool.push({text:s.title,meta:s.maqam,score})}for(const sec of SECTIONS){const n=norm(sec.name);if(n.includes(q)||q.includes(n))pool.push({text:`مقام: ${sec.name}`,meta:'مقام',score:90})}pool.sort((a,b)=>b.score-a.score);const uniq=[];for(const x of pool){if(!uniq.some(y=>y.text===x.text))uniq.push(x);if(uniq.length>=8)break}box.innerHTML='';for(const x of uniq){const b=document.createElement('button');b.className='suggest';b.innerHTML=`<span>${esc(x.text)}</span><small>${esc(x.meta||'')}</small>`;b.onclick=()=>{$('q').value=x.text;box.classList.add('hidden');state.page=1;run()};box.appendChild(b)}box.classList.toggle('hidden',!uniq.length)}

function openModal(id){$(id).classList.add('open');$(id).setAttribute('aria-hidden','false')}function closeModal(id){$(id).classList.remove('open');$(id).setAttribute('aria-hidden','true')}
function getSong(id){return songs().find(s=>s.id===id)||null}
function setTab(name){document.querySelectorAll('#songTabs .tab').forEach(b=>b.classList.toggle('on',b.dataset.tab===name));document.querySelectorAll('#songModal .tab-panel').forEach(p=>p.classList.toggle('active',p.dataset.panel===name));$('songScroll').scrollTop=0}
async function openSong(id){const s=getSong(id);if(!s)return;currentSong=s;$('songTitle').textContent=s.title||'النشيد';$('songQuality').textContent=s.quality?.label||'';$('songQuality').className='badge '+(s.quality?.status==='manual_verified'?'quality-ok':'quality-warn');$('songLyrics').textContent=s.lyrics||s.ocrText||'لا يوجد نص مفهرس لهذا السجل بعد. راجع الصفحة الأصلية.';$('songLyrics').style.fontSize=(settings.font||1.28)+'rem';$('songLyrics').classList.toggle('night',!!settings.night);renderSongInfo(s);renderSourceButtons(s);$('songNote').value=songNote(s.id);renderTagPicker(s.id);renderListPicker(s.id);$('songFav').textContent=favs.has('song:'+s.id)?'★ محفوظ':'☆ مفضلة';$('adminTabBtn').classList.toggle('hidden',!ADMIN);fillAdmin(s);await loadAudio(s);setTab('lyrics');openModal('songModal')}
function renderSongInfo(s){const items=[['المقام',s.maqam],['الفرع',s.branch],['الإيقاع / الوزن',s.rhythm],['الشاعر / الكلمات',s.poet],['الملحن',s.composer],['رقم الشريط',s.tape],['صفحات PDF',(s.pdfPages||[]).join('، ')],['الصفحات المطبوعة',(s.printedPages||[]).join('، ')],['حالة النص',s.transcriptionStatus],['ثقة OCR',s.quality?.confidence?Math.round(s.quality.confidence*100)+'%':'غير محددة']];$('songInfo').innerHTML=items.filter(x=>x[1]).map(([k,v])=>`<div class="info-item"><strong>${esc(k)}</strong>${esc(v)}</div>`).join('');$('songSourceQuality').innerHTML=`${qualityBadge(s)}<span>الأصل المصوّر محفوظ دائماً كمرجع مستقل عن OCR والتصحيح اليدوي.</span>`}
function renderSourceButtons(s){const box=$('sourcePages');box.innerHTML='';if(s.sourceType==='personal'){const b=document.createElement('button');b.className='btn gold';b.textContent='عرض صورة المصدر الشخصية';b.onclick=()=>openCustomSource(s.id);box.appendChild(b);return}for(const n of (s.pdfPages||[])){const b=document.createElement('button');b.className='btn';b.textContent=`PDF ${n}`;b.onclick=()=>openPage(n);box.appendChild(b)}if(!box.children.length)box.textContent='لا توجد صفحة مصدر مرتبطة.'}
function renderTagPicker(id){const box=$('tagPicker');box.innerHTML='';const active=new Set(songTags(id));for(const t of TAGS){const b=document.createElement('button');b.className='tag-pick'+(active.has(t)?' on':'');b.textContent=t;b.onclick=()=>{active.has(t)?active.delete(t):active.add(t);tags[id]=[...active];write(K.tags,tags);renderTagPicker(id);run()};box.appendChild(b)}}
function renderListPicker(id){const box=$('listPicker');box.innerHTML='';const names=Object.keys(lists).sort((a,b)=>a.localeCompare(b,'ar'));if(!names.length){box.innerHTML='<small>لا توجد قوائم بعد. أنشئ قائمة من الحقل أدناه.</small>';return}for(const name of names){const ids=Array.isArray(lists[name])?lists[name]:[];const on=ids.includes(id);const b=document.createElement('button');b.className='tag-pick'+(on?' on':'');b.textContent=name;b.onclick=()=>{const set=new Set(Array.isArray(lists[name])?lists[name]:[]);on?set.delete(id):set.add(id);lists[name]=[...set];write(K.lists,lists);renderListPicker(id)};box.appendChild(b)}}
function fillAdmin(s){$('adTitle').value=s.title||'';$('adMaqam').value=s.maqam||'';$('adBranch').value=s.branch||'';$('adRhythm').value=s.rhythm||'';$('adPoet').value=s.poet||'';$('adComposer').value=s.composer||'';$('adTape').value=s.tape||'';$('adLyrics').value=s.lyrics||s.ocrText||''}

async function loadAudio(s){if(audioObjectUrl){URL.revokeObjectURL(audioObjectUrl);audioObjectUrl=''}const player=$('audioPlayer'),meta=audioMeta[s.id]||{};$('audioUrl').value=meta.url||'';let blob=null;try{blob=await blobGet('audio:'+s.id)}catch{}if(blob){audioObjectUrl=URL.createObjectURL(blob);player.src=audioObjectUrl}else if(meta.url)player.src=meta.url;else player.removeAttribute('src');player.load();renderMarkers(s.id)}
function fmtTime(sec){sec=Math.max(0,Math.floor(Number(sec)||0));return `${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`}
function renderMarkers(id){const box=$('markers');box.innerHTML='';for(const [i,m] of (markers[id]||[]).entries()){const row=document.createElement('div');row.className='marker';row.innerHTML=`<button type="button"><strong>${fmtTime(m.t)}</strong> — ${esc(m.label||'علامة')}</button><button class="btn danger" type="button">×</button>`;row.firstElementChild.onclick=()=>{$('audioPlayer').currentTime=m.t;$('audioPlayer').play().catch(()=>{})};row.lastElementChild.onclick=()=>{markers[id].splice(i,1);write(K.markers,markers);renderMarkers(id)};box.appendChild(row)}if(!box.children.length)box.innerHTML='<small>لا توجد علّامات زمنية بعد.</small>'}

// Page viewer
function setViewerControls(show){viewerControls=show;$('viewerTop').classList.toggle('hidden-controls',!show);$('viewerBottom').classList.toggle('hidden-controls',!show);clearTimeout(viewerTimer);if(show)viewerTimer=setTimeout(()=>setViewerControls(false),4000)}
function setViewerMode(mode){const v=$('viewer');v.classList.remove('mode-image','mode-text','mode-note');v.classList.add('mode-'+mode);$('viewerImageMode').classList.toggle('on',mode==='image');$('viewerTextMode').classList.toggle('on',mode==='text');$('viewerNoteMode').classList.toggle('on',mode==='note');if(mode!=='image')setViewerControls(true)}
function pageSrc(n){if(window.MAQAM_EMBEDDED?.images?.[n])return window.MAQAM_EMBEDDED.images[n];return `./pages/p${String(n).padStart(3,'0')}.jpg`}
function applyViewerZoom(){const stage=$('viewerStage'),img=$('viewerImg');const base=Math.max(280,Math.min(stage.clientWidth||innerWidth,1200));img.style.width=Math.round(base*viewerZoom)+'px';img.style.transform=`rotate(${viewerRotation}deg)`;$('zoomRange').value=Math.round(viewerZoom*100);$('zoomLabel').textContent=Math.round(viewerZoom*100)+'%'}
function openPage(n){currentViewerCustom=null;currentPage=Math.max(1,Math.min(PAGES.length,Number(n)||1));const p=pageMap.get(currentPage);$('viewerTitle').textContent=`صفحة PDF ${currentPage}${p?.maqam?' — '+p.maqam:''}`;$('viewerText').textContent=p?.text||'لا يوجد نص OCR لهذه الصفحة.';$('viewerNote').value=pageNotes[String(currentPage)]||'';$('viewerImg').src=pageSrc(currentPage);$('viewerPrev').disabled=currentPage<=1;$('viewerNext').disabled=currentPage>=PAGES.length;viewerZoom=1;viewerRotation=0;setViewerMode('image');setViewerControls(false);$('viewerHint').classList.remove('hide');setTimeout(()=>$('viewerHint').classList.add('hide'),4200);$('viewer').classList.add('open');$('viewer').setAttribute('aria-hidden','false');$('viewerStage').scrollTo(0,0)}
async function openCustomSource(id){currentViewerCustom=id;const s=getSong(id);const blob=await blobGet('source:'+id).catch(()=>null);if(!blob){toast('لا توجد صورة مصدر محفوظة لهذا السجل.');return}if(audioObjectUrl&&audioObjectUrl.startsWith('blob:')){}const url=URL.createObjectURL(blob);$('viewerImg').src=url;$('viewerImg').dataset.tempUrl=url;$('viewerTitle').textContent=`مصدر شخصي — ${s?.title||''}`;$('viewerText').textContent='مصدر شخصي مضاف من الجهاز.';$('viewerNote').value='';$('viewerPrev').disabled=true;$('viewerNext').disabled=true;viewerZoom=1;viewerRotation=0;setViewerMode('image');setViewerControls(false);$('viewerHint').classList.remove('hide');setTimeout(()=>$('viewerHint').classList.add('hide'),4200);$('viewer').classList.add('open');$('viewer').setAttribute('aria-hidden','false')}
function closeViewer(){const u=$('viewerImg').dataset.tempUrl;if(u){URL.revokeObjectURL(u);delete $('viewerImg').dataset.tempUrl}$('viewer').classList.remove('open');$('viewer').setAttribute('aria-hidden','true');clearTimeout(viewerTimer)}
function openSongSource(s){if(s.sourceType==='personal')openCustomSource(s.id);else openPage((s.pdfPages||[])[0]||1)}

// Performance mode
let perfRAF=0,perfLast=0,wakeLock=null;function perfTick(ts){const speed=Number($('perfSpeed').value)||0;if(speed&&perfLast){$('perfShell').scrollTop+=speed*(ts-perfLast)/1000}perfLast=ts;perfRAF=requestAnimationFrame(perfTick)}
async function wake(enable){try{if(enable&&'wakeLock'in navigator){wakeLock=await navigator.wakeLock.request('screen');$('perfWake').textContent='الشاشة ثابتة ✓'}else if(wakeLock){await wakeLock.release();wakeLock=null;$('perfWake').textContent='إبقاء الشاشة'}}catch{toast('إبقاء الشاشة غير متاح على هذا الجهاز') }}
function openPerformance(){if(!currentSong)return;$('perfTitle').textContent=currentSong.title;$('perfLyrics').textContent=currentSong.lyrics||currentSong.ocrText||'';$('perfLyrics').style.fontSize='';$('perfControls').classList.remove('hide');openModal('performance');perfLast=0;cancelAnimationFrame(perfRAF);perfRAF=requestAnimationFrame(perfTick);document.documentElement.requestFullscreen?.().catch(()=>{})}
function closePerformance(){closeModal('performance');cancelAnimationFrame(perfRAF);wake(false);if(document.fullscreenElement)document.exitFullscreen?.().catch(()=>{})}

function shareUrl(s){const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('song',s.id);return u.href}
async function shareSong(){if(!currentSong)return;const url=shareUrl(currentSong);try{if(navigator.share)await navigator.share({title:currentSong.title,text:`${currentSong.title} — مقام ${currentSong.maqam||''}`,url});else{await navigator.clipboard.writeText(url);toast('تم نسخ رابط النشيد')}}catch{}}
function printSong(){if(!currentSong)return;const s=currentSong,w=window.open('','_blank');if(!w){toast('اسمح بالنوافذ المنبثقة للطباعة');return}w.document.write(`<!doctype html><html dir="rtl"><meta charset="utf-8"><title>${esc(s.title)}</title><style>body{font-family:Tahoma,Arial;max-width:800px;margin:40px auto;line-height:2;color:#12364e}pre{white-space:pre-wrap;font:1.2rem/2 Tahoma,Arial}.meta{color:#666}</style><h1>${esc(s.title)}</h1><div class="meta">المقام: ${esc(s.maqam||'')} ${s.poet?'• الشاعر: '+esc(s.poet):''} ${s.composer?'• الملحن: '+esc(s.composer):''}</div><pre>${esc(s.lyrics||s.ocrText||'')}</pre></html>`);w.document.close();setTimeout(()=>w.print(),250)}

function exportBackup(){const data={format:'MaqamBookBackupV5',version:5,createdAt:new Date().toISOString(),notes,pageNotes,tags,favorites:[...favs],overrides,custom,audioMeta,markers,settings,lists,notice:'الملفات الصوتية والصور الشخصية المخزنة كـ Blob لا تُضمّن في JSON.'};const blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`MaqamBook_Backup_V5_${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importBackup(file){try{const d=JSON.parse(await file.text());if(d.format!=='MaqamBookBackupV5')throw new Error('صيغة غير مدعومة');notes=d.notes||{};pageNotes=d.pageNotes||{};tags=d.tags||{};favs=new Set(d.favorites||[]);overrides=d.overrides||{};custom=d.custom||[];audioMeta=d.audioMeta||{};markers=d.markers||{};settings=d.settings||settings;lists=d.lists||{};write(K.notes,notes);write(K.pageNotes,pageNotes);write(K.tags,tags);write(K.favs,[...favs]);write(K.overrides,overrides);write(K.custom,custom);write(K.audioMeta,audioMeta);write(K.markers,markers);write(K.settings,settings);write(K.lists,lists);toast('تمت استعادة النسخة الاحتياطية');run()}catch(e){toast('تعذر الاستيراد: '+e.message)}}
async function offlineAll(){if(window.MAQAM_EMBEDDED){$('offlineProgress').style.width='100%';$('offlineStatus').textContent='كل صفحات الكتاب مدمجة داخل ملف اللابتوب بالفعل.';toast('هذه النسخة تعمل محلياً والصفحات مدمجة فيها');return}if(!('caches'in window)){toast('التخزين للأوفلاين غير متاح هنا');return}const btn=$('offlineAll'),bar=$('offlineProgress'),st=$('offlineStatus');btn.disabled=true;let done=0,failed=0;const cache=await caches.open('maqambook-pages-v5-user');const paths=PAGES.map(p=>pageSrc(p.n)).filter(x=>!x.startsWith('data:'));let idx=0;async function worker(){while(idx<paths.length){const i=idx++,url=paths[i];try{const hit=await cache.match(url);if(!hit){const r=await fetch(url);if(!r.ok)throw new Error(r.status);await cache.put(url,r.clone())}}catch{failed++}done++;bar.style.width=Math.round(done/paths.length*100)+'%';st.textContent=`${done}/${paths.length}${failed?' — فشل '+failed:''}`}}await Promise.all([worker(),worker(),worker(),worker()]);btn.disabled=false;toast(failed?'انتهى التنزيل مع بعض الملفات المتعذرة':'اكتمل تنزيل صفحات الكتاب للأوفلاين')}

async function addCustom(){const title=$('cuTitle').value.trim();if(!title){toast('اكتب العنوان أولاً');return}const id='custom-'+Date.now();const s={id,title,maqam:$('cuMaqam').value.trim()||'شخصي',poet:$('cuPoet').value.trim(),composer:$('cuComposer').value.trim(),lyrics:$('cuLyrics').value.trim(),ocrText:'',branch:'',rhythm:'',tape:'',pdfPages:[],printedPages:[],sourceType:'personal',quality:{status:'manual_verified',confidence:1,label:'موثق يدوياً ✅'},transcriptionStatus:'مضاف يدوياً'};custom.push(s);write(K.custom,custom);const f=$('cuImage').files[0];if(f)await blobPut('source:'+id,f);['cuTitle','cuMaqam','cuPoet','cuComposer','cuLyrics'].forEach(x=>$(x).value='');$('cuImage').value='';closeModal('customModal');toast('تمت إضافة القصيدة إلى مكتبتك');run();openSong(id)}

function bind(){
$('go').onclick=()=>{state.page=1;run()};$('q').addEventListener('keydown',e=>{if(e.key==='Enter'){state.page=1;$('autocomplete').classList.add('hidden');run()}});$('q').addEventListener('input',()=>{buildSuggestions()});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))$('autocomplete').classList.add('hidden')});document.querySelectorAll('[data-mode]').forEach(b=>b.onclick=()=>{state.mode=b.dataset.mode;document.querySelectorAll('[data-mode]').forEach(x=>x.classList.toggle('on',x===b));state.page=1;run()});$('maqamFilter').onchange=()=>{state.page=1;run()};$('tagFilter').onchange=()=>{state.page=1;run()};$('favOnly').onclick=()=>{state.favOnly=!state.favOnly;$('favOnly').classList.toggle('on',state.favOnly);state.page=1;run()};$('clearSearch').onclick=()=>{$('q').value='';$('maqamFilter').value='';$('tagFilter').value='';state.favOnly=false;$('favOnly').classList.remove('on');state.page=1;run()};
$('songClose').onclick=()=>closeModal('songModal');$('songModal').onclick=e=>{if(e.target===$('songModal'))closeModal('songModal')};document.querySelectorAll('#songTabs .tab').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$('fontMinus').onclick=()=>{settings.font=Math.max(.9,(settings.font||1.28)-.1);$('songLyrics').style.fontSize=settings.font+'rem';write(K.settings,settings)};$('fontPlus').onclick=()=>{settings.font=Math.min(2.4,(settings.font||1.28)+.1);$('songLyrics').style.fontSize=settings.font+'rem';write(K.settings,settings)};$('nightBtn').onclick=()=>{settings.night=!settings.night;$('songLyrics').classList.toggle('night',settings.night);write(K.settings,settings)};$('performanceBtn').onclick=openPerformance;
$('createList').onclick=()=>{if(!currentSong)return;const name=$('newListName').value.trim();if(!name){toast('اكتب اسم القائمة');return}const set=new Set(Array.isArray(lists[name])?lists[name]:[]);set.add(currentSong.id);lists[name]=[...set];write(K.lists,lists);$('newListName').value='';renderListPicker(currentSong.id);toast('تم إنشاء القائمة وإضافة النشيد')};$('saveNote').onclick=()=>{if(!currentSong)return;const v=$('songNote').value.trim();if(v)notes[currentSong.id]=v;else delete notes[currentSong.id];write(K.notes,notes);toast('تم حفظ الملاحظة');run()};$('clearNote').onclick=()=>{if(!currentSong)return;delete notes[currentSong.id];write(K.notes,notes);$('songNote').value='';toast('تم حذف الملاحظة');run()};$('songFav').onclick=()=>{if(!currentSong)return;toggleFav('song:'+currentSong.id);$('songFav').textContent=favs.has('song:'+currentSong.id)?'★ محفوظ':'☆ مفضلة';run()};$('copyLyrics').onclick=async()=>{try{await navigator.clipboard.writeText(currentSong?.lyrics||currentSong?.ocrText||'');toast('تم نسخ الكلمات')}catch{toast('تعذر النسخ على هذا المتصفح')}};$('shareSong').onclick=shareSong;$('printSong').onclick=printSong;$('qrSong').onclick=()=>{if(!currentSong)return;const u=shareUrl(currentSong);$('qrUrl').textContent=u;window.MaqamQR?.draw($('qrCanvas'),u,{size:260});openModal('qrModal')};$('qrClose').onclick=()=>closeModal('qrModal');
$('audioFile').onchange=async()=>{if(!currentSong||!$('audioFile').files[0])return;try{await blobPut('audio:'+currentSong.id,$('audioFile').files[0]);audioMeta[currentSong.id]={...(audioMeta[currentSong.id]||{}),name:$('audioFile').files[0].name};write(K.audioMeta,audioMeta);await loadAudio(currentSong);toast('تم حفظ التسجيل على هذا الجهاز')}catch{toast('تعذر حفظ الملف الصوتي')}};$('audioDelete').onclick=async()=>{if(!currentSong)return;await blobDel('audio:'+currentSong.id).catch(()=>{});await loadAudio(currentSong);toast('تم حذف التسجيل المحلي')};$('audioUrlSave').onclick=()=>{if(!currentSong)return;audioMeta[currentSong.id]={...(audioMeta[currentSong.id]||{}),url:$('audioUrl').value.trim()};write(K.audioMeta,audioMeta);loadAudio(currentSong);toast('تم حفظ رابط التسجيل')};$('addMarker').onclick=()=>{if(!currentSong)return;const t=$('audioPlayer').currentTime||0,label=prompt('اسم العلامة الزمنية، مثال: جواب / انتقال / عودة إلى القرار','')||'';(markers[currentSong.id]||(markers[currentSong.id]=[])).push({t:Math.round(t*10)/10,label});markers[currentSong.id].sort((a,b)=>a.t-b.t);write(K.markers,markers);renderMarkers(currentSong.id)};
$('adminSave').onclick=()=>{if(!currentSong||!ADMIN)return;overrides[currentSong.id]={title:$('adTitle').value.trim(),maqam:$('adMaqam').value.trim(),branch:$('adBranch').value.trim(),rhythm:$('adRhythm').value.trim(),poet:$('adPoet').value.trim(),composer:$('adComposer').value.trim(),tape:$('adTape').value.trim(),lyrics:$('adLyrics').value.trim(),_manual:true};write(K.overrides,overrides);toast('تم حفظ التصحيح كموثق يدوياً');const id=currentSong.id;run();openSong(id)};$('adminReset').onclick=()=>{if(!currentSong)return;delete overrides[currentSong.id];write(K.overrides,overrides);toast('تمت إزالة التصحيح المحلي');const id=currentSong.id;run();openSong(id)};
$('viewerImg').onload=()=>{viewerZoom=1;applyViewerZoom()};$('viewerImg').onclick=()=>setViewerControls(!viewerControls);$('viewerClose').onclick=closeViewer;$('viewer').addEventListener('click',e=>{if(e.target===$('viewer'))closeViewer()});$('viewerPrev').onclick=()=>{if(!currentViewerCustom)openPage(currentPage-1)};$('viewerNext').onclick=()=>{if(!currentViewerCustom)openPage(currentPage+1)};$('viewerImageMode').onclick=()=>setViewerMode('image');$('viewerTextMode').onclick=()=>setViewerMode('text');$('viewerNoteMode').onclick=()=>setViewerMode('note');$('viewerRotate').onclick=()=>{viewerRotation=(viewerRotation+90)%360;applyViewerZoom()};$('zoomRange').oninput=()=>{viewerZoom=Number($('zoomRange').value)/100;applyViewerZoom();setViewerControls(true)};$('zoomMinus').onclick=()=>{viewerZoom=Math.max(.5,viewerZoom-.2);applyViewerZoom();setViewerControls(true)};$('zoomPlus').onclick=()=>{viewerZoom=Math.min(3,viewerZoom+.2);applyViewerZoom();setViewerControls(true)};$('zoomFit').onclick=()=>{viewerZoom=1;viewerRotation=0;applyViewerZoom();$('viewerStage').scrollTo(0,0);setViewerControls(true)};$('viewerNoteSave').onclick=()=>{if(currentViewerCustom)return;const v=$('viewerNote').value.trim();if(v)pageNotes[String(currentPage)]=v;else delete pageNotes[String(currentPage)];write(K.pageNotes,pageNotes);toast('تم حفظ ملاحظة الصفحة')};$('viewerNoteClear').onclick=()=>{if(currentViewerCustom)return;delete pageNotes[String(currentPage)];write(K.pageNotes,pageNotes);$('viewerNote').value='';toast('تم حذف ملاحظة الصفحة')};addEventListener('resize',()=>{if($('viewer').classList.contains('open'))applyViewerZoom()},{passive:true});
$('perfClose').onclick=closePerformance;$('perfSmaller').onclick=()=>{const el=$('perfLyrics'),n=parseFloat(getComputedStyle(el).fontSize);el.style.fontSize=Math.max(18,n-3)+'px'};$('perfLarger').onclick=()=>{const el=$('perfLyrics'),n=parseFloat(getComputedStyle(el).fontSize);el.style.fontSize=Math.min(64,n+3)+'px'};$('perfWake').onclick=()=>wake(!wakeLock);$('perfShell').onclick=e=>{if(e.target===$('perfShell')||e.target===$('perfLyrics'))$('perfControls').classList.toggle('hide')};
$('dataBtn').onclick=()=>openModal('dataModal');$('dataClose').onclick=()=>closeModal('dataModal');$('dataModal').onclick=e=>{if(e.target===$('dataModal'))closeModal('dataModal')};$('backupExport').onclick=exportBackup;$('backupImport').onchange=()=>{$('backupImport').files[0]&&importBackup($('backupImport').files[0]);$('backupImport').value=''};$('offlineAll').onclick=offlineAll;$('customAddBtn').onclick=()=>openModal('customModal');$('customClose').onclick=()=>closeModal('customModal');$('customSave').onclick=addCustom;$('customModal').onclick=e=>{if(e.target===$('customModal'))closeModal('customModal')};
}

async function loadData(){if(window.MAQAM_EMBEDDED){SECTIONS=window.MAQAM_EMBEDDED.sections;PAGES=window.MAQAM_EMBEDDED.pages;BASE_SONGS=window.MAQAM_EMBEDDED.songs}else{const [a,b,c]=await Promise.all([fetch('./data/sections.json'),fetch('./data/pages.json'),fetch('./data/songs.json')]);if(!a.ok||!b.ok||!c.ok)throw new Error('data fetch');[SECTIONS,PAGES,BASE_SONGS]=await Promise.all([a.json(),b.json(),c.json()])}sectionMap=Object.fromEntries(SECTIONS.map(x=>[x.id,x]));pageMap=new Map(PAGES.map(p=>[p.n,p]));$('statusPill').textContent=`${BASE_SONGS.length} سجل • ${PAGES.length} صفحة`;fillFilters();$('adminState').innerHTML=ADMIN?'<span class="badge quality-ok">وضع المدير المحلي مفعّل على هذا الجهاز</span>':'<span class="badge">غير مفعّل</span>';bind();run();const target=new URL(location.href).searchParams.get('song');if(target)setTimeout(()=>openSong(target),100);if('serviceWorker'in navigator&&location.protocol.startsWith('http'))navigator.serviceWorker.register('./sw.js').catch(()=>{})}
loadData().catch(e=>{console.error(e);$('statusPill').textContent='تعذر تحميل الفهرس';$('results').innerHTML='<div class="empty">تعذر تحميل بيانات التطبيق. تأكد من رفع جميع ملفات V5 إلى نفس المجلد.</div>'});
})();
